---
title: "Example-digtization"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Example-digtization}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Example of digitizer workflow

```{r set }
# if not previously installed 
# library(devtools)
# install()
library(SurvdigtizeR)
```

```{r required-packages and ggplot function for plotting}
# Required packages and 
library(dplyr)
library(tidyr)
library(ggplot2)
library(stringr)
library(jpeg)
library(knitr)
library(here)
## We use this function for plotting arrays
fun_ggplot <- function(array, sen = 0.9){
  array%>% as.data.frame() %>%
    mutate(row = 1:n()) %>%
    gather(-row, key= "column", value = "val") %>%
    mutate(column = as.numeric(str_remove_all(column,"V"))) %>%
    filter( val < sen) %>% 
    ggplot(aes(x = column, y = row, fill = val )) +
    geom_tile() 
}
```

```{r}
digtizer_output <- parent_digitizer(curve_location = here("vignettes","KMcurve.png"),
                 sen = 0.3,
                 Wsen_i = 30,
                 OCR_words_i = T,
                 num_curves1 = 2,
                 x_start_i = 0,
                 x_end_i = 10,
                 x_incr = 1,
                 y_start_i = 0,
                 y_end_i = 1,y_incr = 0.25,
                 Y_values_vertical =   T,censoring_i = F )

head(digtizer_output) 
```

